---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint: |
  yamllint
  ansible-lint
platforms:
  - name: test-aws-centos7-adoptium-hotspot-jre-tarball-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptium
      - hotspot
      - jre
      - adoptium_fallback

  - name: test-aws-ubuntu18-adoptium-openj9-jdk-tarball-11
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptium
      - openj9
      - jdk
      - adoptium_fallback

  - name: test-aws-Debian9-adoptium-hotspot-jdk-repositories-11
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptium
      - hotspot
      - jdk
      - repositories

#  - name: test-aws-centos8-adoptium-openj9-jre-repositories-11
#    image: ami-0ed2ad9dc845b42b6
#    platform: centos8
#    instance_type: t3.micro
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.04
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: centos
#    groups:
#      - rhel_family
#      - adoptium
#      - openj9
#      - jre
#      - repositories

  - name: test-aws-centos7-adoptium-local-11
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptium
      - local

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      forks: 30
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      adoptium:
        java_distribution: adoptium
        java_major_version: 11
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptium_impl: openj9
      hotspot:
        adoptium_impl: hotspot
      adoptium_fallback:
        transport: fallback
      repositories:
        transport: repositories
      local:
        transport: local
        transport_local: /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-adoptium-11/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: cloud-aws-adoptium-11
verifier:
  name: ansible
