---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint: |
  yamllint
  ansible-lint
platforms:
#  - name: test-aws-centos8-adoptium-hotspot-jre-repositories-12
#    image: ami-0ed2ad9dc845b42b6
#    platform: centos8
#    instance_type: t3.micro
#    region: us-east-1
#    vpc_subnet_id: subnet-0f2b9cd66faea38af
#    assign_public_ip: false
#    spot_price: 0.04
#    security_group_name:
#      - default
#    wait_timeout: 1800
#    ssh_user: centos
#    groups:
#      - rhel_family
#      - adoptium
#      - hotspot
#      - jre
#      - repositories
#      - pip3

  - name: test-aws-centos7-adoptium-openj9-jdk-tarball-12
    image: ami-9887c6e7
    platform: centos7
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - adoptium
      - openj9
      - jdk
      - adoptium_fallback
      - pip2

  - name: test-aws-Debian9-adoptium-openj9-jre-tarball-12
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptium
      - openj9
      - jre
      - adoptium_fallback
      - pip2

  - name: test-aws-ubuntu18-adoptium-hotspot-jdk-repositories-12
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - adoptium
      - hotspot
      - jdk
      - repositories
      - pip3

  - name: test-aws-Debian9-adoptium-hotspot-jre-repositories-12
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptium
      - hotspot
      - jre
      - repositories
      - pip2

  - name: test-aws-Debian9-adoptium-s3-12
    image: ami-003f19e0e687de1cd
    profile_name: epmldi-instance-profile
    platform: debian9
    instance_type: t3.micro
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - adoptium
      - s3
      - pip2

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      forks: 30
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      pip2:
        pip_executable: pip
        python_executable: python
      pip3:
        pip_executable: pip3
        python_executable: python3
      adoptium:
        java_distribution: adoptium
        java_major_version: 12
      jdk:
        java_package: jdk
      jre:
        java_package: jre
      openj9:
        adoptium_impl: openj9
      hotspot:
        adoptium_impl: hotspot
      adoptium_fallback:
        transport: fallback
      repositories:
        transport: repositories
      s3:
        transport: s3
        transport_s3_bucket: java-molecule-s3-test
        transport_s3_path: /java/adoptium/OpenJDK12U-jdk_x64_linux_hotspot_12.0.1_12.tar.gz
        transport_s3_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        transport_s3_aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../cloud-aws-adoptium-12/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: cloud-aws-adoptium-12
verifier:
  name: ansible
